'use client';
import {useEffect,useState,useRef} from 'react';
import {ArrowUpRight, ArrowRight, Search, Play, X, Mic2, Tv, SlidersHorizontal, ChevronLeft, ChevronRight} from 'lucide-react';
import showsData from './shows.json';
type Episode={title:string;videoId:string;guest:string;duration?:number};
type Show={name:string;host:string;category:string;description:string;episodes:Episode[];sourceUrl?:string;checkedAt?:string;coverVideoId:string;availabilityNote?:string};
const shows=showsData as Show[];
const categories=['All shows','Panel shows','Game shows','Roasts','Advice & banter'];
export default function Home(){
 const [query,setQuery]=useState('');const [episodeQuery,setEpisodeQuery]=useState('');const [category,setCategory]=useState('All shows');const [selected,setSelected]=useState<Show|null>(null);const [spotlightIndex,setSpotlightIndex]=useState(0);const [spotlightPaused,setSpotlightPaused]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 const visible=shows.filter(s=>(category==='All shows'||s.category===category)&&`${s.name} ${s.host}`.toLowerCase().includes(query.toLowerCase()));
 function openShow(s:Show){setEpisodeQuery('');setSelected(s);dialog.current?.showModal()}
 const featured=shows[spotlightIndex]||shows[0];
 useEffect(()=>{if(spotlightPaused)return;const timer=window.setInterval(()=>setSpotlightIndex(index=>(index+1)%shows.length),6500);return()=>window.clearInterval(timer)},[spotlightIndex,spotlightPaused]);
 function moveSpotlight(step:number){setSpotlightIndex(index=>(index+step+shows.length)%shows.length)}
 return <><header><a className="brand" href="#"><span className="brand-icon"><Mic2 size={21}/></span>PANEL<span className="brand-light">CLUB</span><span className="brand-dot">*</span></a><nav><a href="#shows" className="nav-active">Discover shows</a><span className="nav-note">THE INDIAN COMEDY DIRECTORY</span></nav><span className="edition">VOL. 01 <span> / </span> INDIA</span></header>
 <main><section className="intro"><div><div className="eyebrow"><span/> GOOD COMPANY. QUESTIONABLE ADVICE.</div><h1>Your next laugh.<br/><span>All in one place.</span></h1><p>India’s comedy panels, chaotic games and unapologetic roasts.</p></div><div className="intro-note"><span className="asterisk">✳</span><p>{shows.length} shows.<br/>Zero serious conversations.</p></div></section>
 <section className={`spotlight${spotlightPaused?' is-paused':''}`} aria-label="Show spotlight" aria-roledescription="carousel" onMouseEnter={()=>setSpotlightPaused(true)} onMouseLeave={()=>setSpotlightPaused(false)} onFocus={()=>setSpotlightPaused(true)} onBlur={()=>setSpotlightPaused(false)}><div className="spotlight-copy" key={`copy-${featured.name}`}><div className="spotlight-meta"><span className="pill">IN THE SPOTLIGHT</span><span className="feature-category">{featured.category.toUpperCase()}</span><span className="spotlight-counter">{String(spotlightIndex+1).padStart(2,'0')} / {String(shows.length).padStart(2,'0')}</span></div><h2>{featured.name}</h2><p>Hosted by {featured.host}.<br/>{featured.episodes.length} public episodes & parts.</p><button className="primary" onClick={()=>openShow(featured)}><Play size={17} fill="currentColor"/> Explore episodes <ArrowUpRight size={18}/></button><div className="spotlight-controls"><button onClick={()=>moveSpotlight(-1)} aria-label="Previous spotlight show"><ChevronLeft size={18}/></button><div className="spotlight-dots" aria-label={`Slide ${spotlightIndex+1} of ${shows.length}`}>{shows.map((show,index)=><button key={show.name} className={index===spotlightIndex?'active':''} onClick={()=>setSpotlightIndex(index)} aria-label={`Show ${show.name}`} aria-current={index===spotlightIndex?'true':undefined}/>)}</div><button onClick={()=>moveSpotlight(1)} aria-label="Next spotlight show"><ChevronRight size={18}/></button></div><span className="spotlight-progress" aria-hidden="true"><span key={`progress-${spotlightIndex}`}/></span></div><button className="spotlight-image" key={`image-${featured.name}`} onClick={()=>openShow(featured)} aria-label={`Explore ${featured.name}`}><img src={`https://i.ytimg.com/vi/${featured.coverVideoId}/hqdefault.jpg`} alt={`${featured.name} episode 1 thumbnail from YouTube`}/><span className="big-play"><Play size={28} fill="currentColor"/></span><span className="image-caption">{featured.name.toUpperCase()} <ArrowUpRight size={18}/></span></button></section>
 <section id="shows" className="catalogue"><div className="section-head"><div className="section-title"><h2>Find your kind of funny</h2><span>{shows.length.toString().padStart(2,'0')} SHOWS</span></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search shows or hosts" aria-label="Search shows or hosts"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={16}/></button>}</label></div><div className="filter-row"><div className="filters" aria-label="Show categories">{categories.map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><span className="filter-count"><SlidersHorizontal size={15}/> {visible.length} shows</span></div>
 <div className="grid">{visible.map((s,i)=><article className="show-card" key={s.name}><button className="card-image" onClick={()=>openShow(s)} aria-label={`View episodes of ${s.name}`}><img src={`https://i.ytimg.com/vi/${s.coverVideoId}/hqdefault.jpg`} alt={`${s.name} episode 1 thumbnail from YouTube`} loading="lazy"/><span className="card-category">{s.category}</span><span className="cover-episode">EP 01</span><span className="card-play"><Play size={18} fill="currentColor"/></span></button><div className="card-heading"><h3><button onClick={()=>openShow(s)}>{s.name}</button></h3><ArrowUpRight size={18}/></div><p className="host">Hosted by <span>{s.host}</span></p><div className="card-bottom"><button onClick={()=>openShow(s)}><Tv size={15}/> {s.episodes.length} episodes <ArrowRight size={14}/></button></div></article>)}</div>{!visible.length&&<div className="empty"><Search size={30}/><h3>No shows found</h3><p>Try another show name, host, or category.</p><button className="primary" onClick={()=>{setQuery('');setCategory('All shows')}}>View all shows</button></div>}
 </section><footer><a href="#" className="brand">PANEL<span className="brand-light">CLUB</span><span className="brand-dot">*</span></a><p>Made for the love of Indian comedy.</p><span>Thumbnails & episodes via YouTube.</span></footer></main>
 <dialog aria-labelledby="episode-dialog-title" ref={dialog} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}} onClose={()=>setSelected(null)}><div className="dialog-inner">{selected&&<><button className="close" aria-label="Close episodes" onClick={()=>dialog.current?.close()}><X size={22}/></button><span className="eyebrow">{selected.category}</span><h2 id="episode-dialog-title">{selected.name}</h2><p className="dialog-host">Hosted by <strong>{selected.host}</strong></p>{selected.availabilityNote&&<p className="availability-note">{selected.availabilityNote}</p>}<div className="episode-header"><h3>Episodes & parts <span className="episode-total">{selected.episodes.length}</span></h3><span>Public uploads · Watch on YouTube</span></div><label className="search episode-search"><Search size={18}/><input value={episodeQuery} onChange={e=>setEpisodeQuery(e.target.value)} placeholder="Search episodes" aria-label="Search episodes"/>{episodeQuery&&<button onClick={()=>setEpisodeQuery('')} aria-label="Clear episode search"><X size={16}/></button>}</label><div className="episodes">{selected.episodes.filter(ep=>ep.title.toLowerCase().includes(episodeQuery.toLowerCase())).map((ep,i)=><a key={ep.videoId} className="episode" href={`https://www.youtube.com/watch?v=${ep.videoId}`} target="_blank" rel="noreferrer"><div><img src={`https://i.ytimg.com/vi/${ep.videoId}/hqdefault.jpg`} alt={`${ep.title} thumbnail`} loading="lazy"/><span className="episode-play"><Play size={19} fill="currentColor"/></span></div><section><span className="episode-label">YOUTUBE EPISODE</span><h4>{ep.title}</h4><span className="guest episode-guest">Guest <span aria-label="Guest not added">{ep.guest}</span></span><span className="watch">Watch episode <ArrowUpRight size={15}/></span></section></a>)}</div>{episodeQuery&&!selected.episodes.some(ep=>ep.title.toLowerCase().includes(episodeQuery.toLowerCase()))&&<p className="episode-empty">No episodes match “{episodeQuery}”.</p>}<p className="catalogue-note">Public episodes and episode parts checked {selected.checkedAt}. Private, deleted, and members-only videos may be unavailable.</p><a className="more-link" href={selected.sourceUrl||`https://www.youtube.com/results?search_query=${encodeURIComponent(selected.name+' '+selected.host+' full episodes')}`} target="_blank" rel="noreferrer">Open official YouTube catalogue <ArrowUpRight size={17}/></a></>}</div></dialog></>;
}
